"""Create initial tables

Revision ID: e94af60a00b5
Revises: 
Create Date: 2026-04-23 14:24:56.409766

"""
from alembic import op
import sqlalchemy as sa


revision = 'e94af60a00b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empreendimentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('localizacao', sa.String(length=255), nullable=True),
    sa.Column('id_sienge', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sienge')
    )
    op.create_index(op.f('ix_empreendimentos_nome'), 'empreendimentos', ['nome'], unique=False)
    op.create_table('blocos_torres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empreendimento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empreendimento_id'], ['empreendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empreendimento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('id_sienge', sa.String(length=50), nullable=True),
    sa.Column('id_prevision', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empreendimento_id'], ['empreendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicos')
    op.drop_table('blocos_torres')
    op.drop_index(op.f('ix_empreendimentos_nome'), table_name='empreendimentos')
    op.drop_table('empreendimentos')
    # ### end Alembic commands ###
